DE: noreply@seguridad-ies.es
PARA: paco.garcia@ies-seguridad.es
ASUNTO: ⚠️ Alerta de Seguridad: Nuevo inicio de sesión detectado

Hola Paco,

Se ha detectado un inicio de sesión en tu cuenta desde un dispositivo no reconocido.

Fecha: 12 de marzo de 2026, 23:14:50

Ubicación: Ho Chi Minh City, Vietnam (Estimado)

IP: 113.161.192.84

Navegador: Mozilla/5.0 (Unknown Device)

Si no has sido tú, por favor, contacta con el Analista SOC de guardia inmediatamente.
